### ISSUE TITLE
Unity 2017.3.0p1

### ISSUE THREAD

**Issue by markusdf** [jmvogt/Unity-LPC-Character-Animator#7]
Hi there. This doesn't work out of the box on the latest Unity 2017.3 release. 

There appears to be an issue with referencing the sprite atlas object before it has initialised properly (looks like the setup is done in Start() instead of Awake()), and when that is fixed, there are issues creating the lookup dictionaries
- "HU" is not a key in the dictionary (the hurt animations?)
- when we skip the  "HU" sprites, it still throws many errors (tens of thousands) with missing sprites, even though I can see them in the assets folders.

I'll give it a try on my windows box later, incase it's an OSX thing

edit:

yeah definitely an issue still on windows as well. sprites not found and other critical errors

**Comment by jmvogt** [comment]
Thanks for opening this issue. 

It looks like there was an issue with the initial sprite processor that runs upon importing each spritesheet. For some reason, some weren't getting tagged with their full model name. After reimporting a few times the issue seems to have fixed itself.. I can now clone down the repo and load the models successfully out of the box.

Let me know if you are still having issues.

**Comment by jmvogt** [comment]
Seems that the AssetManager is cloning down with models loaded. If that is the case, unload and then reload the models once you open the demo scene.

![image](https://user-images.githubusercontent.com/8921582/34913206-9a5983fa-f8ab-11e7-9b11-c0210ccb316d.png)

**Comment by markusdf** [comment]
Looks good to me! Cheers
